name = "LeanExposition"
version = "0.1.0"
defaultTargets = ["exposition"]

[leanOptions]
autoImplicit = false

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[lean_lib]]
name = "LeanExposition"

[[lean_lib]]
name = "Test"
globs = ["Test", "Test.Collect"]

[[lean_exe]]
name = "exposition"
root = "Main"
supportInterpreter = true
